<?php

/* Debug mode - 0: aus, 1: an, ggfs noch höhere Stufen? */
DEFINE("DEBUG", 1);


/* define directories constants */
DEFINE("DIR_ROOT", __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR);

DEFINE("DIR_CNF", DIR_ROOT . "cnf" . DIRECTORY_SEPARATOR);
DEFINE("DIR_INC", __DIR__ . DIRECTORY_SEPARATOR);
DEFINE("DIR_LANG", DIR_ROOT . "lang" . DIRECTORY_SEPARATOR);
DEFINE("DIR_LIB", DIR_ROOT . "lib" . DIRECTORY_SEPARATOR);
DEFINE("DIR_LOCAL", DIR_ROOT . "local" . DIRECTORY_SEPARATOR);
DEFINE("DIR_TMP", DIR_ROOT . "tmp" . DIRECTORY_SEPARATOR);
DEFINE("DIR_TPL", DIR_ROOT . "tpl" . DIRECTORY_SEPARATOR);
DEFINE("DIR_USERFILES", DIR_ROOT . "userfiles" . DIRECTORY_SEPARATOR);
